### PR TITLE
Use aiohttp in async function

### PR DESCRIPTION
**Pull request by WanderingWizards**
Changed the pageturn function to use aiohttp because it was in an async function and aiohttp is just the slightest bit faster than requests

### CODE REVIEW

**Comment by Kile** [comment]
A few things before I merge this

1) are these changes tested?

2) are these changes proven to be faster?

3) please use self.client.session as the session to make the request

**Comment by WanderingWizards** [comment]
image

It works and it would only be faster by a couple milliseconds.
self.client.session can't be used because this function is not part of the class

**Comment by Kile** [comment]
I pass self to the function, so it can be used

**Comment by WanderingWizards** [comment]
Okay, then yeah it works with self.client.session

**Comment by Kile** [comment]
1) Please fix the lgtm alert

2) Don't use `async with`. This "uses up" the session which is cool when you create and then instantly close the session but not when you want the session to stay open

**Review by Kile — APPROVED** [review]
Alright that seems fine

**Pull request merged**
