### PR TITLE
pxlapi: Refactor cog

### PR DESCRIPTION
**Pull request by fofofofofofofofo**
This should fix numerous bugs and greatly improve performance.

### CODE REVIEW

**Comment by Kile** [comment]
Seems legit

**Comment by rxdn** [comment]
LGTM, merge when ready

**Comment by SafeMoonDev** [comment]
looks good

**Review by SafeMoonDev — APPROVED** [review]

**Comment by Kile** [comment]
I have come to the conclusion that this code is too advanced for me

**Comment by matmen** [comment]
> I have come to the conclusion that this code is too advanced for me

considering yesterdays conversation, this does seem like the case

**Comment by Kile** [comment]
This made me laugh but it is actually sad (and true)

**Pull request closed without merging**
